
meta_product_name: "Pixy secure"
meta_title: "Pixy secure - Une navigation saine et sécurisée"
meta_description: "Extension Chrome pour une navigation saine et sécurisée pour protéger et informer le jeune public sur le vocabulaire inaproprié trop souvent présent sur internet. Une extension pensée pour donner un outils efficace pour les parents et/ou le personnel enseignant."
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
